"""WT_First_Exploration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W_ZECiXCd8foz_HDYPAMY6hr10BYHLKu
"""

import os
print(os.listdir())
#Check which datasets we have uploaded in our colab session

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import streamlit as st
sns.set()





df_Zon = pd.read_csv("app/ZonAnn.Ts+dSST.csv")
st.write(df_Zon.head())

df_Zon_plot1 = plt.figure(figsize = (10,7))
sns.lineplot(x = "Year", y = "Glob", data = df_Zon, label = "Global")
sns.lineplot(x = "Year", y = "NHem", data = df_Zon, label = "Northern Hemisphere")
sns.lineplot(x = "Year", y = "SHem", data = df_Zon, label = "Southern Hemisphere")
df_Zon_plot1.xlabel("Year")
df_Zon_plot1.ylabel("Temperature (ºC change)")
df_Zon_plot1.title("Temperature anomalies")
df_Zon_plot1.legend();

st.pyplot(df_Zon_plot1)
